// Generated by gencpp from file apolloros/MyChassisInfo.msg
// DO NOT EDIT!


#ifndef APOLLOROS_MESSAGE_MYCHASSISINFO_H
#define APOLLOROS_MESSAGE_MYCHASSISINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apolloros
{
template <class ContainerAllocator>
struct MyChassisInfo_
{
  typedef MyChassisInfo_<ContainerAllocator> Type;

  MyChassisInfo_()
    : parking_brake(false)  {
    }
  MyChassisInfo_(const ContainerAllocator& _alloc)
    : parking_brake(false)  {
  (void)_alloc;
    }



   typedef uint8_t _parking_brake_type;
  _parking_brake_type parking_brake;





  typedef boost::shared_ptr< ::apolloros::MyChassisInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apolloros::MyChassisInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MyChassisInfo_

typedef ::apolloros::MyChassisInfo_<std::allocator<void> > MyChassisInfo;

typedef boost::shared_ptr< ::apolloros::MyChassisInfo > MyChassisInfoPtr;
typedef boost::shared_ptr< ::apolloros::MyChassisInfo const> MyChassisInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apolloros::MyChassisInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apolloros::MyChassisInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apolloros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'apolloros': ['/home/txr/apollo_ws/src/apolloros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apolloros::MyChassisInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apolloros::MyChassisInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apolloros::MyChassisInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apolloros::MyChassisInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apolloros::MyChassisInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apolloros::MyChassisInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apolloros::MyChassisInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cc262a21f4d9855085b3835ea61663b";
  }

  static const char* value(const ::apolloros::MyChassisInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cc262a21f4d9855ULL;
  static const uint64_t static_value2 = 0x085b3835ea61663bULL;
};

template<class ContainerAllocator>
struct DataType< ::apolloros::MyChassisInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apolloros/MyChassisInfo";
  }

  static const char* value(const ::apolloros::MyChassisInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apolloros::MyChassisInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool parking_brake\n\
";
  }

  static const char* value(const ::apolloros::MyChassisInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apolloros::MyChassisInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parking_brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyChassisInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apolloros::MyChassisInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apolloros::MyChassisInfo_<ContainerAllocator>& v)
  {
    s << indent << "parking_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.parking_brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APOLLOROS_MESSAGE_MYCHASSISINFO_H
